export const AI_TOOLS_DATA = [
  {
    id: "crewai",
    name: "CrewAI",
    category: "Agentes",
    popularity: 89,
    website: "https://www.crewai.com",
    description: "Equipos de agentes IA que colaboran entre sí.",
    tip: "Define bien los roles para mejores resultados.",
    prompt: "Crea un equipo para investigar un mercado.",
    image: "https://www.google.com/s2/favicons?domain=crewai.com&sz=128"
  },
  {
    id: "flowise",
    name: "Flowise",
    category: "Agentes",
    popularity: 88,
    website: "https://flowiseai.com",
    description: "Crear flujos visuales tipo LangChain.",
    tip: "Ideal para prototipos rápidos de chatbots.",
    prompt: "Crea un flujo que conecte un chatbot con PDF.",
    image: "https://www.google.com/s2/favicons?domain=flowiseai.com&sz=128"
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    category: "Programación",
    popularity: 90,
    website: "https://lmstudio.ai",
    description: "Ejecutar modelos de lenguaje localmente.",
    tip: "Ideal si te preocupa la privacidad.",
    prompt: "Carga un modelo local y úsalo para resumir.",
    image: "https://www.google.com/s2/favicons?domain=lmstudio.ai&sz=128"
  },
  {
    id: "ollama",
    name: "Ollama",
    category: "Programación",
    popularity: 91,
    website: "https://ollama.com",
    description: "Ejecutar LLMs localmente con comandos.",
    tip: "Perfecto para desarrolladores y pruebas offline.",
    prompt: "Ejecuta un modelo local para responder preguntas.",
    image: "https://www.google.com/s2/favicons?domain=ollama.com&sz=128"
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "Programación",
    popularity: 87,
    website: "https://openrouter.ai",
    description: "Acceder a muchos modelos IA desde una API.",
    tip: "Ideal para comparar modelos fácilmente.",
    prompt: "Compara respuestas entre distintos modelos LLM.",
    image: "https://www.google.com/s2/favicons?domain=openrouter.ai&sz=128"
  },
  {
    id: "glean",
    name: "Glean",
    category: "Data",
    popularity: 86,
    website: "https://www.glean.com",
    description: "Búsqueda inteligente interna para empresas.",
    tip: "Ideal para equipos grandes con muchos documentos.",
    prompt: "Encuentra información clave en documentos internos.",
    image: "https://www.google.com/s2/favicons?domain=glean.com&sz=128"
  },
  {
    id: "alphasense",
    name: "AlphaSense",
    category: "Data",
    popularity: 85,
    website: "https://www.alpha-sense.com",
    description: "Inteligencia de mercado con IA.",
    tip: "Muy usada en finanzas y consultoría.",
    prompt: "Analiza tendencias del mercado tecnológico.",
    image: "https://www.google.com/s2/favicons?domain=alpha-sense.com&sz=128"
  },
  {
    id: "crayon",
    name: "Crayon AI",
    category: "Data",
    popularity: 84,
    website: "https://www.crayon.co",
    description: "Análisis competitivo automático.",
    tip: "Ideal para equipos de marketing.",
    prompt: "Monitorea movimientos de la competencia.",
    image: "https://www.google.com/s2/favicons?domain=crayon.co&sz=128"
  },
  {
    id: "tableaugpt",
    name: "Tableau GPT",
    category: "Data",
    popularity: 89,
    website: "https://www.tableau.com",
    description: "Analítica de datos con lenguaje natural.",
    tip: "Pregunta datos como si hablaras con una persona.",
    prompt: "Analiza estas ventas y detecta patrones.",
    image: "https://www.google.com/s2/favicons?domain=tableau.com&sz=128"
  },
  {
    id: "powerbi",
    name: "Power BI Copilot",
    category: "Data",
    popularity: 90,
    website: "https://powerbi.microsoft.com",
    description: "Crear dashboards con IA.",
    tip: "Ideal para usuarios no técnicos.",
    prompt: "Crea un dashboard con métricas clave.",
    image: "https://www.google.com/s2/favicons?domain=powerbi.microsoft.com&sz=128"
  },
  {
    id: "rewind",
    name: "Rewind AI",
    category: "Productividad",
    popularity: 88,
    website: "https://www.rewind.ai",
    description: "Guarda todo lo que ves en tu PC.",
    tip: "Úsalo como memoria externa.",
    prompt: "Encuentra aquella conversación de la semana pasada.",
    image: "https://www.google.com/s2/favicons?domain=rewind.ai&sz=128"
  },
  {
    id: "reflect",
    name: "Reflect AI",
    category: "Productividad",
    popularity: 87,
    website: "https://reflect.app",
    description: "Diario personal con IA para reflexionar.",
    tip: "Ideal para claridad mental.",
    prompt: "Analiza mis notas y detecta patrones emocionales.",
    image: "https://www.google.com/s2/favicons?domain=reflect.app&sz=128"
  },
  {
    id: "sana",
    name: "Sana AI",
    category: "Educación",
    popularity: 86,
    website: "https://www.sana.ai",
    description: "Plataforma de aprendizaje corporativo.",
    tip: "Ideal para capacitación empresarial.",
    prompt: "Crea un curso interno sobre uso de IA.",
    image: "https://www.google.com/s2/favicons?domain=sana.ai&sz=128"
  },
  {
    id: "glass",
    name: "Glass AI",
    category: "Salud",
    popularity: 85,
    website: "https://glass.health",
    description: "Apoyo clínico para médicos.",
    tip: "Uso profesional de salud.",
    prompt: "Analiza síntomas clínicos y sugiere diagnósticos.",
    image: "https://www.google.com/s2/favicons?domain=glass.health&sz=128"
  },
  {
    id: "osmosis",
    name: "Osmosis AI",
    category: "Salud",
    popularity: 84,
    website: "https://www.osmosis.org",
    description: "Educación médica con IA.",
    tip: "Ideal para estudiantes de medicina.",
    prompt: "Explícame este concepto médico de forma simple.",
    image: "https://www.google.com/s2/favicons?domain=osmosis.org&sz=128"
  },
  {
    id: "finch",
    name: "Finch 3D",
    category: "3D",
    popularity: 83,
    website: "https://finch3d.com",
    description: "Diseño arquitectónico asistido por IA.",
    tip: "Ideal para arquitectos.",
    prompt: "Optimiza este diseño arquitectónico.",
    image: "https://www.google.com/s2/favicons?domain=finch3d.com&sz=128"
  },
  {
    id: "testfit",
    name: "TestFit",
    category: "3D",
    popularity: 82,
    website: "https://testfit.io",
    description: "Planificación inmobiliaria automática.",
    tip: "Usado por desarrolladores inmobiliarios.",
    prompt: "Genera un layout óptimo para este terreno.",
    image: "https://www.google.com/s2/favicons?domain=testfit.io&sz=128"
  },
  {
    id: "archistar",
    name: "Archistar",
    category: "3D",
    popularity: 81,
    website: "https://archistar.ai",
    description: "Diseño urbano con IA.",
    tip: "Ideal para planificación urbana.",
    prompt: "Evalúa este terreno para desarrollo urbano.",
    image: "https://www.google.com/s2/favicons?domain=archistar.ai&sz=128"
  },
  {
    id: "planner5d",
    name: "Planner 5D",
    category: "3D",
    popularity: 90,
    website: "https://planner5d.com",
    description: "Diseño de interiores con IA.",
    tip: "Muy visual y fácil.",
    prompt: "Diseña una sala moderna con estilo minimalista.",
    image: "https://www.google.com/s2/favicons?domain=planner5d.com&sz=128"
  },
  {
    id: "nvidia",
    name: "NVIDIA Omniverse",
    category: "3D",
    popularity: 92,
    website: "https://www.nvidia.com/omniverse",
    description: "Simulación 3D y mundos virtuales.",
    tip: "Muy potente (y pesado).",
    prompt: "Simula un entorno industrial realista.",
    image: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=128"
  },
  {
    id: "charisma",
    name: "Charisma AI",
    category: "Juegos",
    popularity: 85,
    website: "https://www.charisma.ai",
    description: "Narrativas interactivas con personajes IA.",
    tip: "Ideal para storytelling.",
    prompt: "Crea una historia interactiva con decisiones.",
    image: "https://www.google.com/s2/favicons?domain=charisma.ai&sz=128"
  },
  {
    id: "convai",
    name: "Convai",
    category: "Juegos",
    popularity: 84,
    website: "https://www.convai.com",
    description: "Conversaciones IA para mundos 3D.",
    tip: "Ideal para VR.",
    prompt: "Crea un NPC conversacional para un mundo virtual.",
    image: "https://www.google.com/s2/favicons?domain=convai.com&sz=128"
  },
  {
    id: "rosebud",
    name: "Rosebud AI",
    category: "Juegos",
    popularity: 83,
    website: "https://www.rosebud.ai",
    description: "Crear juegos con IA sin programar.",
    tip: "Ideal para prototipos.",
    prompt: "Diseña un juego simple de aventura.",
    image: "https://www.google.com/s2/favicons?domain=rosebud.ai&sz=128"
  },
  {
    id: "layer",
    name: "Layer AI",
    category: "Juegos",
    popularity: 82,
    website: "https://www.layer.ai",
    description: "Assets visuales para videojuegos.",
    tip: "Acelera producción gráfica.",
    prompt: "Genera sprites para un juego 2D.",
    image: "https://www.google.com/s2/favicons?domain=layer.ai&sz=128"
  },
  {
    id: "ganimator",
    name: "GANimator",
    category: "Juegos",
    popularity: 81,
    website: "https://ganimator.com",
    description: "Animación generada con IA.",
    tip: "Experimental y creativo.",
    prompt: "Crea una animación artística.",
    image: "https://www.google.com/s2/favicons?domain=ganimator.com&sz=128"
  },
  {
    id: "runwaygen2",
    name: "Runway Gen-2",
    category: "Video",
    popularity: 96,
    website: "https://runwayml.com/gen-2",
    description: "Video a partir de texto o imágenes.",
    tip: "Perfecto para marketing y videos creativos.",
    prompt: "Crea un video de 30 segundos futurista.",
    image: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128"
  },
  {
    id: "pictory",
    name: "Pictory",
    category: "Video",
    popularity: 93,
    website: "https://pictory.ai",
    description: "Convierte textos en videos automáticos.",
    tip: "Ideal para contenidos de redes sociales.",
    prompt: "Transforma este artículo en un video resumido.",
    image: "https://www.google.com/s2/favicons?domain=pictory.ai&sz=128"
  },
  {
    id: "synthesia_2",
    name: "Synthesia",
    category: "Video",
    popularity: 95,
    website: "https://www.synthesia.io",
    description: "Videos con avatares que hablan tu guion.",
    tip: "Añade subtítulos para redes sociales.",
    prompt: "Crea un video explicativo con un avatar.",
    image: "https://www.google.com/s2/favicons?domain=synthesia.io&sz=128"
  },
  {
    id: "veed_2",
    name: "Veed.io",
    category: "Video",
    popularity: 92,
    website: "https://www.veed.io",
    description: "Editor de video con IA y efectos.",
    tip: "Úsalo para mejorar Reels o TikTok.",
    prompt: "Edita este video para hacerlo más dinámico.",
    image: "https://www.google.com/s2/favicons?domain=veed.io&sz=128"
  },
  {
    id: "descript",
    name: "Descript",
    category: "Video",
    popularity: 94,
    website: "https://www.descript.com",
    description: "Edición de audio y video basada en texto.",
    tip: "Borra silencios o palabras con un click.",
    prompt: "Elimina todos los 'eh' y silencios.",
    image: "https://www.google.com/s2/favicons?domain=descript.com&sz=128"
  },
  {
    id: "runwaytext",
    name: "Runway Text to Video",
    category: "Video",
    popularity: 95,
    website: "https://runwayml.com",
    description: "Videos directamente desde prompts.",
    tip: "Ajusta resolución y estilo.",
    prompt: "Video de una playa tropical al atardecer.",
    image: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128"
  },
  {
    id: "boomy",
    name: "Boomy",
    category: "Audio",
    popularity: 88,
    website: "https://boomy.com",
    description: "Crear música original con IA.",
    tip: "Explora géneros distintos.",
    prompt: "Genera una canción electrónica relajante.",
    image: "https://www.google.com/s2/favicons?domain=boomy.com&sz=128"
  },
  {
    id: "soundraw",
    name: "Soundraw",
    category: "Audio",
    popularity: 87,
    website: "https://soundraw.io",
    description: "Composición musical automática.",
    tip: "Ajusta tempo y estilo.",
    prompt: "Crea un tema épico instrumental.",
    image: "https://www.google.com/s2/favicons?domain=soundraw.io&sz=128"
  },
  {
    id: "aiva_2",
    name: "AIVA",
    category: "Audio",
    popularity: 89,
    website: "https://www.aiva.ai",
    description: "Música original para videojuegos y cine.",
    tip: "Ideal para soundtrack sin copyright.",
    prompt: "Compón una pista orquestal inspiradora.",
    image: "https://www.google.com/s2/favicons?domain=aiva.ai&sz=128"
  },
  {
    id: "mubert",
    name: "Mubert",
    category: "Audio",
    popularity: 86,
    website: "https://mubert.com",
    description: "Genera música en streaming con IA.",
    tip: "Ideal para fondo de videos.",
    prompt: "Crea música de fondo relajante.",
    image: "https://www.google.com/s2/favicons?domain=mubert.com&sz=128"
  },
  {
    id: "soundful",
    name: "Soundful",
    category: "Audio",
    popularity: 85,
    website: "https://soundful.com",
    description: "Crear loops y pistas originales.",
    tip: "Perfecto para creadores musicales.",
    prompt: "Genera un loop de hip hop.",
    image: "https://www.google.com/s2/favicons?domain=soundful.com&sz=128"
  },
  {
    id: "canvamagic",
    name: "Canva Magic Studio",
    category: "Imágenes",
    popularity: 97,
    website: "https://www.canva.com/magic-studio",
    description: "Gráficos, banners y presentaciones con IA.",
    tip: "Describe colores y estilo.",
    prompt: "Diseña un banner minimalista.",
    image: "https://www.google.com/s2/favicons?domain=canva.com&sz=128"
  },
  {
    id: "looka",
    name: "Looka",
    category: "Imágenes",
    popularity: 92,
    website: "https://looka.com",
    description: "Diseña logos y branding automáticamente.",
    tip: "Combina estilos para variantes creativas.",
    prompt: "Crea un logo moderno y minimalista.",
    image: "https://www.google.com/s2/favicons?domain=looka.com&sz=128"
  },
  {
    id: "brandmark",
    name: "Brandmark",
    category: "Imágenes",
    popularity: 91,
    website: "https://brandmark.io",
    description: "Branding automático: logos, paletas.",
    tip: "Útil para startups rápidas.",
    prompt: "Genera un branding completo para un café.",
    image: "https://www.google.com/s2/favicons?domain=brandmark.io&sz=128"
  },
  {
    id: "designsai",
    name: "Designs.ai",
    category: "Imágenes",
    popularity: 90,
    website: "https://designs.ai",
    description: "Diseña logos, videos y marketing.",
    tip: "Perfecto para marketing rápido.",
    prompt: "Crea un anuncio animado.",
    image: "https://www.google.com/s2/favicons?domain=designs.ai&sz=128"
  },
  {
    id: "tailorbrands",
    name: "Tailor Brands",
    category: "Imágenes",
    popularity: 89,
    website: "https://www.tailorbrands.com",
    description: "Branding inteligente para empresas.",
    tip: "Útil para logos y colores.",
    prompt: "Crea un logo profesional.",
    image: "https://www.google.com/s2/favicons?domain=tailorbrands.com&sz=128"
  },
  {
    id: "fotor",
    name: "Fotor AI",
    category: "Imágenes",
    popularity: 93,
    website: "https://www.fotor.com",
    description: "Generación y edición de imágenes.",
    tip: "Ideal para marketing visual.",
    prompt: "Genera una imagen de portada.",
    image: "https://www.google.com/s2/favicons?domain=fotor.com&sz=128"
  },
  {
    id: "pixlr",
    name: "Pixlr AI",
    category: "Imágenes",
    popularity: 92,
    website: "https://pixlr.com",
    description: "Editor de fotos con IA.",
    tip: "Perfecto para retoque rápido.",
    prompt: "Elimina fondo y ajusta colores.",
    image: "https://www.google.com/s2/favicons?domain=pixlr.com&sz=128"
  },
  {
    id: "removebg",
    name: "Remove.bg",
    category: "Imágenes",
    popularity: 94,
    website: "https://www.remove.bg",
    description: "Quitar fondo de imágenes al instante.",
    tip: "Ideal para productos.",
    prompt: "Elimina el fondo de esta foto.",
    image: "https://www.google.com/s2/favicons?domain=remove.bg&sz=128"
  },
  {
    id: "icons8",
    name: "Icons8 AI",
    category: "Imágenes",
    popularity: 88,
    website: "https://icons8.com/ai",
    description: "Crear íconos y gráficos con IA.",
    tip: "Útil para UI/UX.",
    prompt: "Genera un set de íconos minimalistas.",
    image: "https://www.google.com/s2/favicons?domain=icons8.com&sz=128"
  },
  {
    id: "artbreeder",
    name: "Artbreeder",
    category: "Imágenes",
    popularity: 89,
    website: "https://www.artbreeder.com",
    description: "Mezcla imágenes para crear arte nuevo.",
    tip: "Ideal para personajes.",
    prompt: "Crea un retrato de fantasía.",
    image: "https://www.google.com/s2/favicons?domain=artbreeder.com&sz=128"
  },
  {
    id: "deepdream",
    name: "Deep Dream Generator",
    category: "Imágenes",
    popularity: 87,
    website: "https://deepdreamgenerator.com",
    description: "Arte surrealista con IA.",
    tip: "Perfecto para experimentación.",
    prompt: "Genera una imagen surrealista.",
    image: "https://www.google.com/s2/favicons?domain=deepdreamgenerator.com&sz=128"
  },
  {
    id: "nightcafe_2",
    name: "NightCafe",
    category: "Imágenes",
    popularity: 91,
    website: "https://nightcafe.studio",
    description: "Generación artística en múltiples estilos.",
    tip: "Explora estilos antes de generar.",
    prompt: "Ilustración estilo óleo.",
    image: "https://www.google.com/s2/favicons?domain=nightcafe.studio&sz=128"
  },
  {
    id: "deepai",
    name: "DeepAI",
    category: "Imágenes",
    popularity: 86,
    website: "https://deepai.org",
    description: "Genera imágenes y efectos visuales.",
    tip: "Experimenta con prompts largos.",
    prompt: "Crea un paisaje apocalíptico.",
    image: "https://www.google.com/s2/favicons?domain=deepai.org&sz=128"
  },
  {
    id: "craiyon",
    name: "Craiyon",
    category: "Imágenes",
    popularity: 85,
    website: "https://www.craiyon.com",
    description: "Genera imágenes rápidas.",
    tip: "Útil para pruebas visuales.",
    prompt: "Dibuja un robot amigable.",
    image: "https://www.google.com/s2/favicons?domain=craiyon.com&sz=128"
  },
  {
    id: "zapier_2",
    name: "Zapier AI",
    category: "Automatización",
    popularity: 95,
    website: "https://zapier.com/ai",
    description: "Automatizar tareas entre apps.",
    tip: "Ideal para ahorrar trabajo.",
    prompt: "Automatiza envío de correos.",
    image: "https://www.google.com/s2/favicons?domain=zapier.com&sz=128"
  },
  {
    id: "make_2",
    name: "Make",
    category: "Automatización",
    popularity: 94,
    website: "https://www.make.com",
    description: "Flujos automatizados con IA.",
    tip: "Más avanzado que Zapier.",
    prompt: "Crea un flujo complejo de datos.",
    image: "https://www.google.com/s2/favicons?domain=make.com&sz=128"
  },
  {
    id: "ifttt",
    name: "IFTTT AI",
    category: "Automatización",
    popularity: 92,
    website: "https://ifttt.com",
    description: "Conecta apps y dispositivos.",
    tip: "Útil para casa inteligente.",
    prompt: "Envíame mensaje al recibir correo.",
    image: "https://www.google.com/s2/favicons?domain=ifttt.com&sz=128"
  },
  {
    id: "parabola",
    name: "Parabola",
    category: "Automatización",
    popularity: 90,
    website: "https://parabola.io",
    description: "Automatización de datos sin código.",
    tip: "Perfecto para marketing.",
    prompt: "Limpia y combina datos de clientes.",
    image: "https://www.google.com/s2/favicons?domain=parabola.io&sz=128"
  },
  {
    id: "tray",
    name: "Tray.io",
    category: "Automatización",
    popularity: 89,
    website: "https://tray.io",
    description: "Integración empresarial.",
    tip: "Ideal para empresas grandes.",
    prompt: "Conecta Salesforce con HubSpot.",
    image: "https://www.google.com/s2/favicons?domain=tray.io&sz=128"
  },
  {
    id: "datarobot",
    name: "DataRobot",
    category: "Data",
    popularity: 88,
    website: "https://www.datarobot.com",
    description: "Machine learning automatizado.",
    tip: "Predice resultados de negocio.",
    prompt: "Predice la rotación de clientes.",
    image: "https://www.google.com/s2/favicons?domain=datarobot.com&sz=128"
  },
  {
    id: "h2o",
    name: "H2O.ai",
    category: "Data",
    popularity: 87,
    website: "https://www.h2o.ai",
    description: "Plataforma de análisis y ML.",
    tip: "Ideal para científicos de datos.",
    prompt: "Entrena un modelo de fraude.",
    image: "https://www.google.com/s2/favicons?domain=h2o.ai&sz=128"
  },
  {
    id: "monkeylearn",
    name: "MonkeyLearn",
    category: "Data",
    popularity: 86,
    website: "https://monkeylearn.com",
    description: "Análisis de texto y sentimiento.",
    tip: "Perfecto para opiniones.",
    prompt: "Clasifica comentarios positivos/negativos.",
    image: "https://www.google.com/s2/favicons?domain=monkeylearn.com&sz=128"
  },
  {
    id: "rapidminer",
    name: "RapidMiner",
    category: "Data",
    popularity: 85,
    website: "https://rapidminer.com",
    description: "Análisis de datos y predicciones.",
    tip: "Herramienta todo-en-uno.",
    prompt: "Genera un modelo de ventas.",
    image: "https://www.google.com/s2/favicons?domain=rapidminer.com&sz=128"
  },
  {
    id: "bigml",
    name: "BigML",
    category: "Data",
    popularity: 84,
    website: "https://bigml.com",
    description: "Machine learning visual.",
    tip: "Ideal si no programas.",
    prompt: "Crea modelo de riesgo crediticio.",
    image: "https://www.google.com/s2/favicons?domain=bigml.com&sz=128"
  },
  {
    id: "growbots",
    name: "Growbots",
    category: "Marketing",
    popularity: 88,
    website: "https://www.growbots.com",
    description: "Generación de leads B2B.",
    tip: "Automatiza prospección.",
    prompt: "Encuentra 50 leads de software.",
    image: "https://www.google.com/s2/favicons?domain=growbots.com&sz=128"
  },
  {
    id: "leadiq",
    name: "LeadIQ",
    category: "Marketing",
    popularity: 87,
    website: "https://leadiq.com",
    description: "Captura leads automáticamente.",
    tip: "Conecta con CRMs.",
    prompt: "Extrae datos de esta lista.",
    image: "https://www.google.com/s2/favicons?domain=leadiq.com&sz=128"
  },
  {
    id: "outreach",
    name: "Outreach",
    category: "Marketing",
    popularity: 90,
    website: "https://www.outreach.io",
    description: "Automatización de ventas.",
    tip: "Seguimiento automático.",
    prompt: "Crea secuencia de 3 emails.",
    image: "https://www.google.com/s2/favicons?domain=outreach.io&sz=128"
  },
  {
    id: "salesloft",
    name: "SalesLoft",
    category: "Marketing",
    popularity: 89,
    website: "https://salesloft.com",
    description: "Gestión de ventas con IA.",
    tip: "Mejora efectividad.",
    prompt: "Prioriza leads calientes.",
    image: "https://www.google.com/s2/favicons?domain=salesloft.com&sz=128"
  },
  {
    id: "apollo_2",
    name: "Apollo.io",
    category: "Marketing",
    popularity: 92,
    website: "https://www.apollo.io",
    description: "CRM y prospección.",
    tip: "Ideal para B2B.",
    prompt: "Genera lista de leads fintech.",
    image: "https://www.google.com/s2/favicons?domain=apollo.io&sz=128"
  },
  {
    id: "hubspot_2",
    name: "HubSpot AI",
    category: "Marketing",
    popularity: 95,
    website: "https://www.hubspot.com",
    description: "Marketing y ventas integrado.",
    tip: "Centraliza gestión.",
    prompt: "Prioriza leads y sugiere pasos.",
    image: "https://www.google.com/s2/favicons?domain=hubspot.com&sz=128"
  },
  {
    id: "notion_2",
    name: "Notion AI",
    category: "Productividad",
    popularity: 96,
    website: "https://www.notion.so/product/ai",
    description: "Notas y resúmenes automáticos.",
    tip: "Organiza proyectos.",
    prompt: "Resume reunión y lista tareas.",
    image: "https://www.google.com/s2/favicons?domain=notion.so&sz=128"
  },
  {
    id: "coda",
    name: "Coda AI",
    category: "Productividad",
    popularity: 91,
    website: "https://coda.io",
    description: "Documentos inteligentes.",
    tip: "Automatiza reportes.",
    prompt: "Crea resumen con KPIs.",
    image: "https://www.google.com/s2/favicons?domain=coda.io&sz=128"
  },
  {
    id: "craft",
    name: "Craft AI",
    category: "Productividad",
    popularity: 89,
    website: "https://craft.co",
    description: "Organizar información.",
    tip: "Perfecto para investigación.",
    prompt: "Extrae insights clave.",
    image: "https://www.google.com/s2/favicons?domain=craft.co&sz=128"
  },
  {
    id: "mem_2",
    name: "Mem AI",
    category: "Productividad",
    popularity: 88,
    website: "https://mem.ai",
    description: "Notas que recuerdan contexto.",
    tip: "No olvides ideas.",
    prompt: "Genera recordatorios importantes.",
    image: "https://www.google.com/s2/favicons?domain=mem.ai&sz=128"
  },
  {
    id: "supernormal",
    name: "Supernormal",
    category: "Reuniones",
    popularity: 87,
    website: "https://supernormal.com",
    description: "Automatiza actas de reuniones.",
    tip: "Ideal para muchas reuniones.",
    prompt: "Destaca decisiones clave.",
    image: "https://www.google.com/s2/favicons?domain=supernormal.com&sz=128"
  },
  {
    id: "fireflies_2",
    name: "Fireflies AI",
    category: "Reuniones",
    popularity: 92,
    website: "https://fireflies.ai",
    description: "Transcripción de reuniones.",
    tip: "Integra con Zoom/Meet.",
    prompt: "Transcribe reunión de 45 min.",
    image: "https://www.google.com/s2/favicons?domain=fireflies.ai&sz=128"
  },
  {
    id: "sembly_2",
    name: "Sembly AI",
    category: "Reuniones",
    popularity: 90,
    website: "https://www.sembly.ai",
    description: "Resúmenes y análisis.",
    tip: "Detecta tareas pendientes.",
    prompt: "Lista tareas y responsables.",
    image: "https://www.google.com/s2/favicons?domain=sembly.ai&sz=128"
  },
  {
    id: "fellow_2",
    name: "Fellow AI",
    category: "Reuniones",
    popularity: 89,
    website: "https://fellow.app",
    description: "Seguimiento de reuniones.",
    tip: "Mejora productividad.",
    prompt: "Crea agenda optimizada.",
    image: "https://www.google.com/s2/favicons?domain=fellow.app&sz=128"
  },
  {
    id: "grain",
    name: "Grain",
    category: "Reuniones",
    popularity: 88,
    website: "https://grain.com",
    description: "Comparte clips de reuniones.",
    tip: "Ideal para resúmenes.",
    prompt: "Extrae momentos importantes.",
    image: "https://www.google.com/s2/favicons?domain=grain.com&sz=128"
  },
  {
    id: "hotpot",
    name: "Hotpot AI",
    category: "Imágenes",
    popularity: 87,
    website: "https://hotpot.ai",
    description: "Restauración de fotos y efectos.",
    tip: "Retoque rápido.",
    prompt: "Restaura esta imagen antigua.",
    image: "https://www.google.com/s2/favicons?domain=hotpot.ai&sz=128"
  },
  {
    id: "photoroom_2",
    name: "PhotoRoom",
    category: "Imágenes",
    popularity: 93,
    website: "https://www.photoroom.com",
    description: "Imágenes de producto para e-commerce.",
    tip: "Elimina fondos fácil.",
    prompt: "Agrega sombra realista.",
    image: "https://www.google.com/s2/favicons?domain=photoroom.com&sz=128"
  },
  {
    id: "fiverr",
    name: "Fiverr AI",
    category: "Imágenes",
    popularity: 86,
    website: "https://www.fiverr.com/ai",
    description: "Creación automática para freelancers.",
    tip: "Explora estilos.",
    prompt: "Genera un logo profesional.",
    image: "https://www.google.com/s2/favicons?domain=fiverr.com&sz=128"
  },
  {
    id: "copyai_2",
    name: "Copy.ai",
    category: "Escritura",
    popularity: 94,
    website: "https://www.copy.ai",
    description: "Marketing y textos.",
    tip: "Combina prompts largos.",
    prompt: "Escribe email persuasivo.",
    image: "https://www.google.com/s2/favicons?domain=copy.ai&sz=128"
  },
  {
    id: "jasper_2",
    name: "Jasper AI",
    category: "Escritura",
    popularity: 95,
    website: "https://www.jasper.ai",
    description: "Redacción para marketing.",
    tip: "Contenido largo creativo.",
    prompt: "Escribe artículo de 800 palabras.",
    image: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=128"
  },
  {
    id: "writesonic_2",
    name: "Writesonic",
    category: "Escritura",
    popularity: 93,
    website: "https://writesonic.com",
    description: "Blogs y anuncios con IA.",
    tip: "Templates para social media.",
    prompt: "Crea captions para Instagram.",
    image: "https://www.google.com/s2/favicons?domain=writesonic.com&sz=128"
  },
  {
    id: "anyword_2",
    name: "Anyword",
    category: "Marketing",
    popularity: 88,
    website: "https://anyword.com",
    description: "Copywriting de conversiones.",
    tip: "Analiza rendimiento.",
    prompt: "Escribe anuncio que convierta.",
    image: "https://www.google.com/s2/favicons?domain=anyword.com&sz=128"
  },
  {
    id: "scalenut",
    name: "Scalenut",
    category: "Escritura",
    popularity: 87,
    website: "https://www.scalenut.com",
    description: "Contenido SEO optimizado.",
    tip: "Combina IA y análisis.",
    prompt: "Crea artículo SEO.",
    image: "https://www.google.com/s2/favicons?domain=scalenut.com&sz=128"
  },
  {
    id: "peppertype",
    name: "Peppertype.ai",
    category: "Escritura",
    popularity: 86,
    website: "https://www.peppertype.ai",
    description: "Generación rápida de ideas.",
    tip: "Brainstorming de marketing.",
    prompt: "Genera ideas de captions.",
    image: "https://www.google.com/s2/favicons?domain=peppertype.ai&sz=128"
  },
  {
    id: "simplified",
    name: "Simplified",
    category: "Imágenes",
    popularity: 89,
    website: "https://simplified.com",
    description: "Diseño, video y marketing.",
    tip: "Todo-en-uno.",
    prompt: "Crea banner animado.",
    image: "https://www.google.com/s2/favicons?domain=simplified.com&sz=128"
  },
  {
    id: "endel",
    name: "Endel",
    category: "Audio",
    popularity: 90,
    website: "https://endel.io",
    description: "Música para concentración.",
    tip: "Ajusta ambiente.",
    prompt: "Crea pista de concentración.",
    image: "https://www.google.com/s2/favicons?domain=endel.io&sz=128"
  },
  {
    id: "brainfm",
    name: "Brain.fm",
    category: "Audio",
    popularity: 89,
    website: "https://www.brain.fm",
    description: "Música para enfoque.",
    tip: "Ideal para estudiar.",
    prompt: "Genera música para concentrarme.",
    image: "https://www.google.com/s2/favicons?domain=brain.fm&sz=128"
  },
  {
    id: "audo",
    name: "Audo.ai",
    category: "Audio",
    popularity: 88,
    website: "https://audo.ai",
    description: "Limpia audio automáticamente.",
    tip: "Ideal para podcasts.",
    prompt: "Elimina ruido de fondo.",
    image: "https://www.google.com/s2/favicons?domain=audo.ai&sz=128"
  },
  {
    id: "cleanvoice",
    name: "Cleanvoice AI",
    category: "Audio",
    popularity: 87,
    website: "https://cleanvoice.ai",
    description: "Elimina muletillas.",
    tip: "Perfecto para YouTube.",
    prompt: "Elimina 'eh' y 'um'.",
    image: "https://www.google.com/s2/favicons?domain=cleanvoice.ai&sz=128"
  },
  {
    id: "lalal",
    name: "LALAL.AI",
    category: "Audio",
    popularity: 91,
    website: "https://www.lalal.ai",
    description: "Separación de voces e instrumentos.",
    tip: "Ideal para remixes.",
    prompt: "Extrae voz principal.",
    image: "https://www.google.com/s2/favicons?domain=lalal.ai&sz=128"
  },
  {
    id: "deepmotion",
    name: "DeepMotion",
    category: "Imágenes",
    popularity: 86,
    website: "https://www.deepmotion.com",
    description: "Captura de movimiento 3D.",
    tip: "Ideal para videojuegos.",
    prompt: "Convierte video en animación.",
    image: "https://www.google.com/s2/favicons?domain=deepmotion.com&sz=128"
  },
  {
    id: "moveai",
    name: "Move.ai",
    category: "Imágenes",
    popularity: 85,
    website: "https://move.ai",
    description: "Captura de movimiento corporal.",
    tip: "Úsalo para animaciones.",
    prompt: "Genera modelo de animación.",
    image: "https://www.google.com/s2/favicons?domain=move.ai&sz=128"
  },
  {
    id: "plask",
    name: "Plask",
    category: "Imágenes",
    popularity: 84,
    website: "https://www.plask.ai",
    description: "Edición de animaciones.",
    tip: "Prototipos rápidos.",
    prompt: "Anima personaje 3D.",
    image: "https://www.google.com/s2/favicons?domain=plask.ai&sz=128"
  },
  {
    id: "deepnostalgia",
    name: "Deep Nostalgia",
    category: "Imágenes",
    popularity: 92,
    website: "https://www.myheritage.com/deep-nostalgia",
    description: "Anima fotos antiguas.",
    tip: "Ideal para recuerdos.",
    prompt: "Anima esta foto.",
    image: "https://www.google.com/s2/favicons?domain=myheritage.com&sz=128"
  },
  {
    id: "avatarify",
    name: "Avatarify",
    category: "Imágenes",
    popularity: 89,
    website: "https://avatarify.ai",
    description: "Avatares animados.",
    tip: "Úsalo en conferencias.",
    prompt: "Crea avatar animado.",
    image: "https://www.google.com/s2/favicons?domain=avatarify.ai&sz=128"
  },
  {
    id: "characterai",
    name: "Character.ai",
    category: "Chatbots",
    popularity: 96,
    website: "https://beta.character.ai",
    description: "Personajes conversacionales.",
    tip: "Historias interactivas.",
    prompt: "Crea personaje divertido.",
    image: "https://www.google.com/s2/favicons?domain=character.ai&sz=128"
  },
  {
    id: "replika",
    name: "Replika",
    category: "Chatbots",
    popularity: 91,
    website: "https://replika.ai",
    description: "Chatbot de compañía.",
    tip: "Desarrollo emocional.",
    prompt: "Conversación diaria.",
    image: "https://www.google.com/s2/favicons?domain=replika.ai&sz=128"
  },
  {
    id: "aidungeon_2",
    name: "AI Dungeon",
    category: "Juegos",
    popularity: 88,
    website: "https://www.aidungeon.com",
    description: "Juegos de rol narrativos.",
    tip: "Ideal para storytelling.",
    prompt: "Inicia aventura.",
    image: "https://www.google.com/s2/favicons?domain=aidungeon.com&sz=128"
  },
  {
    id: "inworld_2",
    name: "Inworld AI",
    category: "Juegos",
    popularity: 87,
    website: "https://www.inworld.ai",
    description: "Personajes para metaverso.",
    tip: "Personalidad propia.",
    prompt: "Crea NPC sarcástico.",
    image: "https://www.google.com/s2/favicons?domain=inworld.ai&sz=128"
  },
  {
    id: "prompthub",
    name: "Prompthub",
    category: "Productividad",
    popularity: 90,
    website: "https://prompthub.ai",
    description: "Biblioteca de prompts.",
    tip: "Optimiza resultados.",
    prompt: "Busca prompts efectivos.",
    image: "https://www.google.com/s2/favicons?domain=prompthub.ai&sz=128"
  },

  // =======================================================
  // 101-200: BLOQUE FINAL (CORREGIDO Y LIMPIO)
  // =======================================================
  {
    id: "crewai",
    name: "CrewAI",
    category: "Agentes",
    popularity: 89,
    website: "https://www.crewai.com",
    description: "Crear equipos de agentes IA que colaboran entre sí (cada uno con un rol).",
    tip: "Define bien los roles para mejores resultados.",
    prompt: "Crea un equipo de agentes para investigar un mercado y generar un informe.",
    image: "https://www.google.com/s2/favicons?domain=crewai.com&sz=128"
  },
  {
    id: "flowise",
    name: "Flowise",
    category: "Agentes",
    popularity: 88,
    website: "https://flowiseai.com",
    description: "Crear flujos visuales tipo LangChain sin tanto código.",
    tip: "Ideal para prototipos rápidos de chatbots.",
    prompt: "Crea un flujo que conecte un chatbot con documentos PDF.",
    image: "https://www.google.com/s2/favicons?domain=flowiseai.com&sz=128"
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    category: "Programación",
    popularity: 90,
    website: "https://lmstudio.ai",
    description: "Ejecutar modelos de lenguaje localmente (en tu PC).",
    tip: "Ideal si te preocupa la privacidad.",
    prompt: "Carga un modelo local y úsalo para resumir documentos.",
    image: "https://www.google.com/s2/favicons?domain=lmstudio.ai&sz=128"
  },
  {
    id: "ollama",
    name: "Ollama",
    category: "Programación",
    popularity: 91,
    website: "https://ollama.com",
    description: "Ejecutar LLMs localmente con comandos simples.",
    tip: "Perfecto para desarrolladores y pruebas offline.",
    prompt: "Ejecuta un modelo local para responder preguntas técnicas.",
    image: "https://www.google.com/s2/favicons?domain=ollama.com&sz=128"
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "Programación",
    popularity: 87,
    website: "https://openrouter.ai",
    description: "Acceder a muchos modelos IA desde una sola API.",
    tip: "Ideal para comparar modelos fácilmente.",
    prompt: "Compara respuestas entre distintos modelos LLM.",
    image: "https://www.google.com/s2/favicons?domain=openrouter.ai&sz=128"
  },
  {
    id: "glean",
    name: "Glean",
    category: "Data",
    popularity: 86,
    website: "https://www.glean.com",
    description: "Búsqueda inteligente interna para empresas.",
    tip: "Ideal para equipos grandes con muchos documentos.",
    prompt: "Encuentra información clave en documentos internos.",
    image: "https://www.google.com/s2/favicons?domain=glean.com&sz=128"
  },
  {
    id: "alphasense",
    name: "AlphaSense",
    category: "Data",
    popularity: 85,
    website: "https://www.alpha-sense.com",
    description: "Inteligencia de mercado con IA.",
    tip: "Muy usada en finanzas y consultoría.",
    prompt: "Analiza tendencias del mercado tecnológico.",
    image: "https://www.google.com/s2/favicons?domain=alpha-sense.com&sz=128"
  },
  {
    id: "crayon",
    name: "Crayon AI",
    category: "Data",
    popularity: 84,
    website: "https://www.crayon.co",
    description: "Análisis competitivo automático.",
    tip: "Ideal para equipos de marketing.",
    prompt: "Monitorea movimientos de la competencia.",
    image: "https://www.google.com/s2/favicons?domain=crayon.co&sz=128"
  },
  {
    id: "tableaugpt",
    name: "Tableau GPT",
    category: "Data",
    popularity: 89,
    website: "https://www.tableau.com",
    description: "Analítica de datos con lenguaje natural.",
    tip: "Pregunta datos como si hablaras con una persona.",
    prompt: "Analiza estas ventas y detecta patrones.",
    image: "https://www.google.com/s2/favicons?domain=tableau.com&sz=128"
  },
  {
    id: "powerbi",
    name: "Power BI Copilot",
    category: "Data",
    popularity: 90,
    website: "https://powerbi.microsoft.com",
    description: "Crear dashboards con IA.",
    tip: "Ideal para usuarios no técnicos.",
    prompt: "Crea un dashboard con métricas clave del negocio.",
    image: "https://www.google.com/s2/favicons?domain=powerbi.microsoft.com&sz=128"
  },
  {
    id: "rewind",
    name: "Rewind AI",
    category: "Productividad",
    popularity: 88,
    website: "https://www.rewind.ai",
    description: "Guarda todo lo que ves en tu computadora y lo vuelve buscable.",
    tip: "Úsalo como memoria externa.",
    prompt: "Encuentra aquella conversación importante de la semana pasada.",
    image: "https://www.google.com/s2/favicons?domain=rewind.ai&sz=128"
  },
  {
    id: "reflect",
    name: "Reflect AI",
    category: "Productividad",
    popularity: 87,
    website: "https://reflect.app",
    description: "Diario personal con IA para reflexionar.",
    tip: "Ideal para claridad mental.",
    prompt: "Analiza mis notas y detecta patrones emocionales.",
    image: "https://www.google.com/s2/favicons?domain=reflect.app&sz=128"
  },
  {
    id: "sana",
    name: "Sana AI",
    category: "Educación",
    popularity: 86,
    website: "https://www.sana.ai",
    description: "Plataforma de aprendizaje corporativo con IA.",
    tip: "Ideal para capacitación empresarial.",
    prompt: "Crea un curso interno sobre uso de IA.",
    image: "https://www.google.com/s2/favicons?domain=sana.ai&sz=128"
  },
  {
    id: "glass",
    name: "Glass AI",
    category: "Salud",
    popularity: 85,
    website: "https://glass.health",
    description: "Apoyo clínico para médicos.",
    tip: "Uso profesional de salud.",
    prompt: "Analiza síntomas clínicos y sugiere diagnósticos posibles.",
    image: "https://www.google.com/s2/favicons?domain=glass.health&sz=128"
  },
  {
    id: "osmosis",
    name: "Osmosis AI",
    category: "Salud",
    popularity: 84,
    website: "https://www.osmosis.org",
    description: "Educación médica con IA.",
    tip: "Ideal para estudiantes de medicina.",
    prompt: "Explícame este concepto médico de forma simple.",
    image: "https://www.google.com/s2/favicons?domain=osmosis.org&sz=128"
  },
  {
    id: "finch",
    name: "Finch 3D",
    category: "3D",
    popularity: 83,
    website: "https://finch3d.com",
    description: "Diseño arquitectónico asistido por IA.",
    tip: "Ideal para arquitectos.",
    prompt: "Optimiza este diseño arquitectónico.",
    image: "https://www.google.com/s2/favicons?domain=finch3d.com&sz=128"
  },
  {
    id: "testfit",
    name: "TestFit",
    category: "3D",
    popularity: 82,
    website: "https://testfit.io",
    description: "Planificación inmobiliaria automática.",
    tip: "Usado por desarrolladores inmobiliarios.",
    prompt: "Genera un layout óptimo para este terreno.",
    image: "https://www.google.com/s2/favicons?domain=testfit.io&sz=128"
  },
  {
    id: "archistar",
    name: "Archistar",
    category: "3D",
    popularity: 81,
    website: "https://archistar.ai",
    description: "Diseño urbano con IA.",
    tip: "Ideal para planificación urbana.",
    prompt: "Evalúa este terreno para desarrollo urbano.",
    image: "https://www.google.com/s2/favicons?domain=archistar.ai&sz=128"
  },
  {
    id: "planner5d_2",
    name: "Planner 5D",
    category: "3D",
    popularity: 90,
    website: "https://planner5d.com",
    description: "Diseño de interiores con IA.",
    tip: "Muy visual y fácil.",
    prompt: "Diseña una sala moderna con estilo minimalista.",
    image: "https://www.google.com/s2/favicons?domain=planner5d.com&sz=128"
  },
  {
    id: "nvidia",
    name: "NVIDIA Omniverse",
    category: "3D",
    popularity: 92,
    website: "https://www.nvidia.com/omniverse",
    description: "Simulación 3D y mundos virtuales.",
    tip: "Muy potente (y pesado).",
    prompt: "Simula un entorno industrial realista.",
    image: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=128"
  },
  {
    id: "charisma",
    name: "Charisma AI",
    category: "Juegos",
    popularity: 85,
    website: "https://www.charisma.ai",
    description: "Narrativas interactivas con personajes IA.",
    tip: "Ideal para storytelling.",
    prompt: "Crea una historia interactiva con decisiones morales.",
    image: "https://www.google.com/s2/favicons?domain=charisma.ai&sz=128"
  },
  {
    id: "convai",
    name: "Convai",
    category: "Juegos",
    popularity: 84,
    website: "https://www.convai.com",
    description: "Conversaciones IA para mundos 3D y juegos.",
    tip: "Ideal para VR.",
    prompt: "Crea un NPC conversacional para un mundo virtual.",
    image: "https://www.google.com/s2/favicons?domain=convai.com&sz=128"
  },
  {
    id: "rosebud",
    name: "Rosebud AI",
    category: "Juegos",
    popularity: 83,
    website: "https://www.rosebud.ai",
    description: "Crear juegos con IA sin programar.",
    tip: "Ideal para prototipos.",
    prompt: "Diseña un juego simple de aventura.",
    image: "https://www.google.com/s2/favicons?domain=rosebud.ai&sz=128"
  },
  {
    id: "layer",
    name: "Layer AI",
    category: "Juegos",
    popularity: 82,
    website: "https://www.layer.ai",
    description: "Assets visuales para videojuegos.",
    tip: "Acelera producción gráfica.",
    prompt: "Genera sprites para un juego 2D.",
    image: "https://www.google.com/s2/favicons?domain=layer.ai&sz=128"
  },
  {
    id: "ganimator",
    name: "GANimator",
    category: "Juegos",
    popularity: 81,
    website: "https://ganimator.com",
    description: "Animación generada con IA.",
    tip: "Experimental y creativo.",
    prompt: "Crea una animación artística a partir de imágenes.",
    image: "https://www.google.com/s2/favicons?domain=ganimator.com&sz=128"
  },
  {
    id: "runwaygen2_2",
    name: "Runway Gen-2",
    category: "Video",
    popularity: 96,
    website: "https://runwayml.com/gen-2",
    description: "Generación de video a partir de texto o imágenes.",
    tip: "Perfecto para marketing y videos creativos.",
    prompt: "Crea un video de 30 segundos mostrando una ciudad futurista al amanecer.",
    image: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128"
  },
  {
    id: "pictory",
    name: "Pictory",
    category: "Video",
    popularity: 93,
    website: "https://pictory.ai",
    description: "Convierte artículos y textos en videos automáticos.",
    tip: "Ideal para contenidos de redes sociales.",
    prompt: "Transforma este artículo en un video resumido de 1 minuto.",
    image: "https://www.google.com/s2/favicons?domain=pictory.ai&sz=128"
  },
  {
    id: "synthesia_3",
    name: "Synthesia",
    category: "Video",
    popularity: 95,
    website: "https://www.synthesia.io",
    description: "Videos con avatares que hablan tu guion.",
    tip: "Añade subtítulos para redes sociales.",
    prompt: "Crea un video explicativo sobre productividad con un avatar profesional.",
    image: "https://www.google.com/s2/favicons?domain=synthesia.io&sz=128"
  },
  {
    id: "veed_3",
    name: "Veed.io",
    category: "Video",
    popularity: 92,
    website: "https://www.veed.io",
    description: "Editor de video con IA, subtítulos automáticos y efectos.",
    tip: "Úsalo para mejorar Reels o TikTok.",
    prompt: "Edita este video para hacerlo más dinámico y atractivo.",
    image: "https://www.google.com/s2/favicons?domain=veed.io&sz=128"
  },
  {
    id: "descript",
    name: "Descript",
    category: "Video",
    popularity: 94,
    website: "https://www.descript.com",
    description: "Edición de audio y video basada en texto.",
    tip: "Borra silencios o palabras con un click.",
    prompt: "Elimina todos los 'eh' y silencios de este audio.",
    image: "https://www.google.com/s2/favicons?domain=descript.com&sz=128"
  },
  {
    id: "runwaytext",
    name: "Runway Text to Video",
    category: "Video",
    popularity: 95,
    website: "https://runwayml.com",
    description: "Generar videos directamente desde prompts de texto.",
    tip: "Ajusta resolución y estilo para mejor resultado.",
    prompt: "Video de una playa tropical al atardecer, estilo cinematográfico.",
    image: "https://www.google.com/s2/favicons?domain=runwayml.com&sz=128"
  },
  {
    id: "boomy",
    name: "Boomy",
    category: "Audio",
    popularity: 88,
    website: "https://boomy.com",
    description: "Crear música original con IA en segundos.",
    tip: "Explora géneros distintos para inspiración.",
    prompt: "Genera una canción electrónica relajante de 2 minutos.",
    image: "https://www.google.com/s2/favicons?domain=boomy.com&sz=128"
  },
  {
    id: "soundraw",
    name: "Soundraw",
    category: "Audio",
    popularity: 87,
    website: "https://soundraw.io",
    description: "Composición musical automática para videos.",
    tip: "Ajusta tempo y estilo según tu contenido.",
    prompt: "Crea un tema épico instrumental de 60 segundos.",
    image: "https://www.google.com/s2/favicons?domain=soundraw.io&sz=128"
  },
  {
    id: "aiva_3",
    name: "AIVA",
    category: "Audio",
    popularity: 89,
    website: "https://www.aiva.ai",
    description: "Música original para videojuegos, cine y videos.",
    tip: "Ideal para crear soundtrack sin copyright.",
    prompt: "Compón una pista orquestal inspiradora para un trailer.",
    image: "https://www.google.com/s2/favicons?domain=aiva.ai&sz=128"
  },
  {
    id: "mubert",
    name: "Mubert",
    category: "Audio",
    popularity: 86,
    website: "https://mubert.com",
    description: "Genera música en streaming con IA.",
    tip: "Ideal para fondo de videos o livestreams.",
    prompt: "Crea música de fondo relajante para estudio.",
    image: "https://www.google.com/s2/favicons?domain=mubert.com&sz=128"
  },
  {
    id: "soundful",
    name: "Soundful",
    category: "Audio",
    popularity: 85,
    website: "https://soundful.com",
    description: "Crear loops y pistas de música originales.",
    tip: "Perfecto para creadores de contenido musical.",
    prompt: "Genera un loop de hip hop de 30 segundos.",
    image: "https://www.google.com/s2/favicons?domain=soundful.com&sz=128"
  },
  {
    id: "canvamagic",
    name: "Canva Magic Studio",
    category: "Imágenes",
    popularity: 97,
    website: "https://www.canva.com/magic-studio",
    description: "Genera gráficos, banners y presentaciones con IA.",
    tip: "Describe colores, estilo y sensación para mejores resultados.",
    prompt: "Diseña un banner minimalista para una campaña de email marketing.",
    image: "https://www.google.com/s2/favicons?domain=canva.com&sz=128"
  },
  {
    id: "looka",
    name: "Looka",
    category: "Imágenes",
    popularity: 92,
    website: "https://looka.com",
    description: "Diseña logos y branding automáticamente.",
    tip: "Combina estilos para obtener variantes creativas.",
    prompt: "Crea un logo moderno y minimalista para un startup de tecnología.",
    image: "https://www.google.com/s2/favicons?domain=looka.com&sz=128"
  },
  {
    id: "brandmark",
    name: "Brandmark",
    category: "Imágenes",
    popularity: 91,
    website: "https://brandmark.io",
    description: "Branding automático: logos, paletas y tipografía.",
    tip: "Útil para startups que quieren prototipos rápidos.",
    prompt: "Genera un branding completo para un café moderno.",
    image: "https://www.google.com/s2/favicons?domain=brandmark.io&sz=128"
  },
  {
    id: "designsai",
    name: "Designs.ai",
    category: "Imágenes",
    popularity: 90,
    website: "https://designs.ai",
    description: "Diseña logos, videos y material de marketing con IA.",
    tip: "Perfecto para marketing rápido.",
    prompt: "Crea un anuncio animado para redes sociales sobre moda sostenible.",
    image: "https://www.google.com/s2/favicons?domain=designs.ai&sz=128"
  },
  {
    id: "tailorbrands",
    name: "Tailor Brands",
    category: "Imágenes",
    popularity: 89,
    website: "https://www.tailorbrands.com",
    description: "Branding inteligente para empresas pequeñas.",
    tip: "Útil para logos y paletas de colores.",
    prompt: "Crea un logo profesional y moderno para una agencia digital.",
    image: "https://www.google.com/s2/favicons?domain=tailorbrands.com&sz=128"
  },
  {
    id: "fotor",
    name: "Fotor AI",
    category: "Imágenes",
    popularity: 93,
    website: "https://www.fotor.com",
    description: "Generación y edición de imágenes con IA.",
    tip: "Ideal para marketing y contenido visual rápido.",
    prompt: "Genera una imagen de portada para un ebook sobre productividad.",
    image: "https://www.google.com/s2/favicons?domain=fotor.com&sz=128"
  },
  {
    id: "pixlr",
    name: "Pixlr AI",
    category: "Imágenes",
    popularity: 92,
    website: "https://pixlr.com",
    description: "Editor de fotos con IA y efectos automáticos.",
    tip: "Perfecto para retoque rápido.",
    prompt: "Elimina fondo y ajusta colores de esta imagen.",
    image: "https://www.google.com/s2/favicons?domain=pixlr.com&sz=128"
  },
  {
    id: "removebg",
    name: "Remove.bg",
    category: "Imágenes",
    popularity: 94,
    website: "https://www.remove.bg",
    description: "Quitar fondo de imágenes al instante.",
    tip: "Ideal para productos y e-commerce.",
    prompt: "Elimina el fondo de esta foto de producto.",
    image: "https://www.google.com/s2/favicons?domain=remove.bg&sz=128"
  },
  {
    id: "icons8",
    name: "Icons8 AI",
    category: "Imágenes",
    popularity: 88,
    website: "https://icons8.com/ai",
    description: "Crear íconos y gráficos con IA.",
    tip: "Útil para UI/UX y apps.",
    prompt: "Genera un set de íconos minimalistas para una app financiera.",
    image: "https://www.google.com/s2/favicons?domain=icons8.com&sz=128"
  },
  {
    id: "artbreeder",
    name: "Artbreeder",
    category: "Imágenes",
    popularity: 89,
    website: "https://www.artbreeder.com",
    description: "Mezcla imágenes para crear arte nuevo.",
    tip: "Ideal para crear personajes y escenarios.",
    prompt: "Crea un retrato de un personaje de fantasía combinando dos imágenes.",
    image: "https://www.google.com/s2/favicons?domain=artbreeder.com&sz=128"
  },
  {
    id: "deepdream",
    name: "Deep Dream Generator",
    category: "Imágenes",
    popularity: 87,
    website: "https://deepdreamgenerator.com",
    description: "Arte surrealista con IA.",
    tip: "Perfecto para experimentación creativa.",
    prompt: "Genera una imagen surrealista de un bosque iluminado.",
    image: "https://www.google.com/s2/favicons?domain=deepdreamgenerator.com&sz=128"
  },
  {
    id: "nightcafe_3",
    name: "NightCafe",
    category: "Imágenes",
    popularity: 91,
    website: "https://nightcafe.studio",
    description: "Generación artística con IA en múltiples estilos.",
    tip: "Explora estilos antes de generar.",
    prompt: "Ilustración estilo óleo de una ciudad futurista al atardecer.",
    image: "https://www.google.com/s2/favicons?domain=nightcafe.studio&sz=128"
  },
  {
    id: "deepai",
    name: "DeepAI",
    category: "Imágenes",
    popularity: 86,
    website: "https://deepai.org",
    description: "Genera imágenes y efectos visuales con IA.",
    tip: "Experimenta con prompts largos y descriptivos.",
    prompt: "Crea un paisaje apocalíptico estilo realista.",
    image: "https://www.google.com/s2/favicons?domain=deepai.org&sz=128"
  },
  {
    id: "craiyon",
    name: "Craiyon",
    category: "Imágenes",
    popularity: 85,
    website: "https://www.craiyon.com",
    description: "Genera imágenes rápidas y experimentales.",
    tip: "Útil para pruebas rápidas de ideas visuales.",
    prompt: "Dibuja un robot amigable caminando por una ciudad futurista.",
    image: "https://www.google.com/s2/favicons?domain=craiyon.com&sz=128"
  },
  {
    id: "hotpot",
    name: "Hotpot AI",
    category: "Imágenes",
    popularity: 87,
    website: "https://hotpot.ai",
    description: "Generación de imágenes, restauración de fotos y efectos creativos.",
    tip: "Perfecto para retoque rápido y marketing visual.",
    prompt: "Restaura esta imagen antigua y mejora colores sin perder detalles.",
    image: "https://www.google.com/s2/favicons?domain=hotpot.ai&sz=128"
  },
  {
    id: "photoroom_3",
    name: "PhotoRoom",
    category: "Imágenes",
    popularity: 93,
    website: "https://www.photoroom.com",
    description: "Elimina fondos y crea imágenes de producto listas para e-commerce.",
    tip: "Ideal para vender en marketplaces y redes sociales.",
    prompt: "Elimina el fondo y agrega sombra realista a este producto.",
    image: "https://www.google.com/s2/favicons?domain=photoroom.com&sz=128"
  },
  {
    id: "fiverr",
    name: "Fiverr AI",
    category: "Imágenes",
    popularity: 86,
    website: "https://www.fiverr.com/ai",
    description: "Herramientas de creación automática para freelancers.",
    tip: "Explora múltiples estilos y crea prototipos rápidos.",
    prompt: "Genera un logo profesional para una agencia de marketing digital.",
    image: "https://www.google.com/s2/favicons?domain=fiverr.com&sz=128"
  },
  {
    id: "copyai_3",
    name: "Copy.ai",
    category: "Escritura",
    popularity: 94,
    website: "https://www.copy.ai",
    description: "Generación de textos, slogans, emails y marketing.",
    tip: "Combina prompts largos con ejemplos para mejores resultados.",
    prompt: "Escribe un email persuasivo para vender un curso online de productividad.",
    image: "https://www.google.com/s2/favicons?domain=copy.ai&sz=128"
  },
  {
    id: "jasper_3",
    name: "Jasper AI",
    category: "Escritura",
    popularity: 95,
    website: "https://www.jasper.ai",
    description: "Redacción asistida con IA para marketing y blogs.",
    tip: "Ideal para generar contenido largo y creativo rápidamente.",
    prompt: "Escribe un artículo de 800 palabras sobre IA en educación.",
    image: "https://www.google.com/s2/favicons?domain=jasper.ai&sz=128"
  },
  {
    id: "writesonic_3",
    name: "Writesonic",
    category: "Escritura",
    popularity: 93,
    website: "https://writesonic.com",
    description: "Generar blogs, anuncios, descripciones y más con IA.",
    tip: "Explora templates para social media y SEO.",
    prompt: "Crea 5 captions atractivos para Instagram sobre viajes.",
    image: "https://www.google.com/s2/favicons?domain=writesonic.com&sz=128"
  },
  {
    id: "anyword_3",
    name: "Anyword",
    category: "Marketing",
    popularity: 88,
    website: "https://anyword.com",
    description: "Copywriting enfocado en conversiones y marketing.",
    tip: "Analiza predicciones de rendimiento de cada texto.",
    prompt: "Escribe un anuncio de Facebook que convierta para un curso de cocina online.",
    image: "https://www.google.com/s2/favicons?domain=anyword.com&sz=128"
  },
  {
    id: "scalenut",
    name: "Scalenut",
    category: "Escritura",
    popularity: 87,
    website: "https://www.scalenut.com",
    description: "Contenido SEO optimizado y generación de blogs con IA.",
    tip: "Combina IA + análisis de competencia para mejores resultados.",
    prompt: "Crea un artículo SEO optimizado sobre productividad con IA.",
    image: "https://www.google.com/s2/favicons?domain=scalenut.com&sz=128"
  },
  {
    id: "peppertype",
    name: "Peppertype.ai",
    category: "Escritura",
    popularity: 86,
    website: "https://www.peppertype.ai",
    description: "Generación rápida de ideas de contenido y textos cortos.",
    tip: "Perfecto para brainstorming de marketing y redes.",
    prompt: "Genera 10 ideas de captions creativos para TikTok.",
    image: "https://www.google.com/s2/favicons?domain=peppertype.ai&sz=128"
  },
  {
    id: "simplified",
    name: "Simplified",
    category: "Imágenes",
    popularity: 89,
    website: "https://simplified.com",
    description: "Diseño gráfico, videos, marketing y redacción con IA.",
    tip: "Todo-en-uno para emprendedores y creadores de contenido.",
    prompt: "Crea un banner animado para promocionar un webinar.",
    image: "https://www.google.com/s2/favicons?domain=simplified.com&sz=128"
  },
  {
    id: "endel",
    name: "Endel",
    category: "Audio",
    popularity: 90,
    website: "https://endel.io",
    description: "Música personalizada para concentración, relajación o sueño.",
    tip: "Ajusta tiempo y ambiente según tu necesidad.",
    prompt: "Crea una pista de concentración de 30 minutos para trabajar.",
    image: "https://www.google.com/s2/favicons?domain=endel.io&sz=128"
  },
  {
    id: "brainfm",
    name: "Brain.fm",
    category: "Audio",
    popularity: 89,
    website: "https://www.brain.fm",
    description: "Música que mejora enfoque, relajación y sueño usando IA.",
    tip: "Ideal para estudiar o meditar.",
    prompt: "Genera música de 45 minutos que me ayude a concentrarme.",
    image: "https://www.google.com/s2/favicons?domain=brain.fm&sz=128"
  },
  {
    id: "audo",
    name: "Audo.ai",
    category: "Audio",
    popularity: 88,
    website: "https://audo.ai",
    description: "Mejora y limpia audio automáticamente.",
    tip: "Ideal para podcasts y grabaciones profesionales.",
    prompt: "Limpia este audio eliminando ruido de fondo y eco.",
    image: "https://www.google.com/s2/favicons?domain=audo.ai&sz=128"
  },
  {
    id: "cleanvoice",
    name: "Cleanvoice AI",
    category: "Audio",
    popularity: 87,
    website: "https://cleanvoice.ai",
    description: "Elimina muletillas y errores de audio con IA.",
    tip: "Perfecto para podcasts y videos de YouTube.",
    prompt: "Elimina 'eh' y 'um' de esta grabación de 10 minutos.",
    image: "https://www.google.com/s2/favicons?domain=cleanvoice.ai&sz=128"
  },
  {
    id: "lalal",
    name: "LALAL.AI",
    category: "Audio",
    popularity: 91,
    website: "https://www.lalal.ai",
    description: "Separación de voces e instrumentos de canciones con IA.",
    tip: "Ideal para remixes y producción musical.",
    prompt: "Extrae la voz principal de esta canción para karaoke.",
    image: "https://www.google.com/s2/favicons?domain=lalal.ai&sz=128"
  },
  {
    id: "deepmotion",
    name: "DeepMotion",
    category: "Imágenes",
    popularity: 86,
    website: "https://www.deepmotion.com",
    description: "Captura de movimiento y animaciones para personajes 3D.",
    tip: "Ideal para videojuegos y VR.",
    prompt: "Convierte este video en animación 3D para un personaje.",
    image: "https://www.google.com/s2/favicons?domain=deepmotion.com&sz=128"
  },
  {
    id: "moveai",
    name: "Move.ai",
    category: "Imágenes",
    popularity: 85,
    website: "https://move.ai",
    description: "Seguimiento de movimiento y captura de cuerpo completo con IA.",
    tip: "Úsalo para animaciones de películas o juegos.",
    prompt: "Genera un modelo de animación a partir de este video de referencia.",
    image: "https://www.google.com/s2/favicons?domain=move.ai&sz=128"
  },
  {
    id: "plask",
    name: "Plask",
    category: "Imágenes",
    popularity: 84,
    website: "https://www.plask.ai",
    description: "Captura de movimiento y edición de animaciones en tiempo real.",
    tip: "Combina con personajes 3D para prototipos rápidos.",
    prompt: "Anima un personaje 3D usando este video de referencia.",
    image: "https://www.google.com/s2/favicons?domain=plask.ai&sz=128"
  },
  {
    id: "deepnostalgia",
    name: "Deep Nostalgia",
    category: "Imágenes",
    popularity: 92,
    website: "https://www.myheritage.com/deep-nostalgia",
    description: "Anima fotos antiguas con IA.",
    tip: "Ideal para recuerdos familiares.",
    prompt: "Anima esta foto antigua para que la persona sonría y parpadee.",
    image: "https://www.google.com/s2/favicons?domain=myheritage.com&sz=128"
  },
  {
    id: "avatarify",
    name: "Avatarify",
    category: "Imágenes",
    popularity: 89,
    website: "https://avatarify.ai",
    description: "Creación de avatares animados para videos y conferencias.",
    tip: "Úsalo en Zoom o Twitch para reemplazar tu rostro.",
    prompt: "Crea un avatar animado que hable mi guion en tiempo real.",
    image: "https://www.google.com/s2/favicons?domain=avatarify.ai&sz=128"
  },
  {
    id: "characterai",
    name: "Character.ai",
    category: "Chatbots",
    popularity: 96,
    website: "https://beta.character.ai",
    description: "Crear personajes conversacionales inteligentes.",
    tip: "Perfecto para historias interactivas o asistentes virtuales.",
    prompt: "Crea un personaje que enseñe matemáticas de forma divertida.",
    image: "https://www.google.com/s2/favicons?domain=character.ai&sz=128"
  },
  {
    id: "replika",
    name: "Replika",
    category: "Chatbots",
    popularity: 91,
    website: "https://replika.ai",
    description: "Chatbot de compañía y desarrollo emocional.",
    tip: "Puedes entrenarlo para que tenga tu estilo de conversación.",
    prompt: "Conversación diaria para mejorar mi estado de ánimo.",
    image: "https://www.google.com/s2/favicons?domain=replika.ai&sz=128"
  },
  {
    id: "aidungeon_3",
    name: "AI Dungeon",
    category: "Juegos",
    popularity: 88,
    website: "https://www.aidungeon.com",
    description: "Aventuras de rol generadas por IA.",
    tip: "Ideal para escribir historias interactivas.",
    prompt: "Inicia una aventura en un mundo de fantasía oscura.",
    image: "https://www.google.com/s2/favicons?domain=aidungeon.com&sz=128"
  },
  {
    id: "inworld_3",
    name: "Inworld AI",
    category: "Juegos",
    popularity: 87,
    website: "https://www.inworld.ai",
    description: "Personajes con IA para videojuegos y metaverso.",
    tip: "Cada personaje puede tener personalidad propia.",
    prompt: "Crea un NPC sarcástico que interactúe con jugadores.",
    image: "https://www.google.com/s2/favicons?domain=inworld.ai&sz=128"
  },
  {
    id: "prompthub",
    name: "Prompthub",
    category: "Productividad",
    popularity: 90,
    website: "https://prompthub.ai",
    description: "Biblioteca de prompts para todo tipo de IA.",
    tip: "Aprende de prompts creados por expertos y optimiza tus resultados.",
    prompt: "Busca y prueba prompts efectivos para generar arte hiperrealista.",
    image: "https://www.google.com/s2/favicons?domain=prompthub.ai&sz=128"
  }
];

  

